### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by simonmysun** [simonmysun/indoor-sound-classification-frontend#9]
* [x] live data UI remake
* [x] alert rules editor
* [x] alert rules check
* [x] alert generate config file and sighub prometheus
* [ ] alert get last fired timestamp
* [x] query history data: different views in different tabs
* [x] home page filling
* [x] Thesis
